<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.iflytek</groupId>
        <artifactId>interview-ai</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>interview-bootstrap</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- 聚合业务模块 -->
        <dependency>
            <groupId>com.iflytek</groupId>
            <artifactId>interview-system</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iflytek</groupId>
            <artifactId>interview-interview</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iflytek</groupId>
            <artifactId>interview-job</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iflytek</groupId>
            <artifactId>interview-question</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iflytek</groupId>
            <artifactId>interview-file</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <mainClass>com.iflytek.interview.InterviewAiApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
